<?php
$_helper = $this->helper('googlereviews');
$_accountId = $_helper->getAccountId();
$_position = $_helper->getBadgePosition();
?>
<script src="https://apis.google.com/js/platform.js?onload=renderBadge" async defer></script>
<script>
    window.renderBadge = function() {
        var ratingBadgeContainer = document.createElement("div");
        document.body.appendChild(ratingBadgeContainer);
        window.gapi.load('ratingbadge', function() {
            window.gapi.ratingbadge.render(ratingBadgeContainer, {
                "merchant_id": <?php echo $_accountId ?>,
                "position": "BOTTOM_LEFT"
            });
        });
    }
</script>